version: "3"

services:
  analyzer:
    build:
      context: .
      dockerfile: analyzer/api/Dockerfile
    command: gunicorn  -b 0.0.0.0:5000 main:app --reload
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1

    ports:
      - "5000:5000"
    volumes:
    - ./analyzer:/root/
    - ./database:/root/database
    links:
      - db

  distributor:
    build:
      context: .
      dockerfile: distributor/api/Dockerfile
    environment:
      - TOKEN=${TOKEN}
    command: python main.py
    ports:
      - "5001:5001"
    volumes:
      - ./distributor:/root/
      - ./database:/root/database
    links:
      - db

  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asdfghjkl-9151290
      POSTGRES_DB: poll_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: