version: "3"


services:
  data_distributor:
    build:
      context: .
      dockerfile: data_distributor/api/Dockerfile
    command: gunicorn --workers=5 -b 0.0.0.0:6060 main:app --reload
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "6060:6060"
    volumes:
    - ./data_distributor:/root/
    - ./data_distributor:/root/data_distributor
    links:
      - db



  bot:
    build:
      context: .
      dockerfile: bot/api/Dockerfile
    environment:
      - TOKEN=${TOKEN}
    command: python main.py
    ports:
      - "5001:5001"
    volumes:
      - ./bot:/root/
    links:
      - db
      - data_distributor



  analyzer:
    build:
      context: .
      dockerfile: analyzer/api/Dockerfile
    command: python main.py
    ports:
      - "6061:6061"
    volumes:
      - ./analyzer:/root/
    links:
      - data_distributor


  web:
    build:
      context: .
      dockerfile: web/api/Dockerfile
    command: gunicorn --workers=2 -b 0.0.0.0:6070 web.main:app --reload
    ports:
      - "6070:6070"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./web:/root/web
      - ./analyzer/data:/root/data



  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asdfghjkl-9151290
      POSTGRES_DB: poll_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
